CREATE TABLE IF NOT EXISTS dim_customer AS SELECT * FROM (SELECT CAST(NULL AS INTEGER) AS customer_id) WHERE FALSE;
CREATE TABLE IF NOT EXISTS dim_store AS SELECT * FROM (SELECT CAST(NULL AS INTEGER) AS store_id) WHERE FALSE;
CREATE TABLE IF NOT EXISTS dim_market AS SELECT * FROM (SELECT CAST(NULL AS VARCHAR) AS market) WHERE FALSE;
CREATE TABLE IF NOT EXISTS dim_campaign AS SELECT * FROM (SELECT CAST(NULL AS VARCHAR) AS campaign) WHERE FALSE;
CREATE TABLE IF NOT EXISTS dim_sector_finance AS SELECT * FROM (SELECT CAST(NULL AS VARCHAR) AS sector) WHERE FALSE;
